image: ruby:3.0

stages:
  - triage

dry-run:triage:
  stage: triage
  script:
    - gem install khulnasoft-triage
    - khulnasoft-triage --help
    - khulnasoft-triage --dry-run --token $KHULNASOFT_API_TOKEN --host-url $CI_SERVER_URL --source projects --source-id $CI_PROJECT_PATH
  when: manual
  except:
    - schedules

run:triage:
  stage: triage
  script:
    - gem install khulnasoft-triage
    - khulnasoft-triage --token $KHULNASOFT_API_TOKEN --host-url $CI_SERVER_URL --source projects --source-id $CI_PROJECT_PATH
  only:
    - schedules
